apiVersion: v1
kind: Service
metadata:
  name: mongodbrouterservice
  labels:
    name: mongorouter
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    role: mongorouter

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodbrouterstateful
spec:
  selector:
    matchLabels:
      role: mongorouter
  serviceName: mongodbrouterservice
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: mongorouter
        replicaset: mongorouters
    spec:
      containers:
        - name: mongodroutercontainer
          image: mongo:3.6.2
          command:
            - "mongos"
            - "--configdb"
            - "mongoreplicaset1config/10.43.0.130:27017,10.43.1.66:27017,10.43.1.194:27017"
            - "--bind_ip_all"
            - "--port"
            - "27017"
          ports:
            - containerPort: 27017
          volumeMounts:           
            - name: mongodbrouterpvc
              mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodbrouterpvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi