apiVersion: v1
kind: Service
metadata:
  name: mongodbrouterservice
  labels:
    name: mongorouter
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    role: mongorouter

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodbrouterstateful
spec:
  selector:
    matchLabels:
      role: mongorouter
  serviceName: mongodbrouterservice
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: mongorouter
        replicaset: mongorouters
    spec:
      containers:
        - name: mongodroutercontainer
          image: mongo:3.6.2
          command:
            - "mongos"
            - "--configdb"
            - "mongoreplicaset1config/10.43.0.133:27017,10.43.1.69:27017,10.43.1.2:27017"
            - "--bind_ip_all"
            - "--port"
            - "27017"
          ports:
            - containerPort: 27017
          volumeMounts:           
            - name: mongodbrouterpvc
              mountPath: /data/db
          resources:
            limits:
              cpu: "1"
              memory: "200Mi"
            requests:
              cpu: "0.1"
              memory: "100Mi"
      nodeSelector:
        failure-domain.beta.kubernetes.io/region: us-central1
        failure-domain.beta.kubernetes.io/zone: us-central1-b
  volumeClaimTemplates:
  - metadata:
      name: mongodbrouterpvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: us-central1-b-sc-1
      resources:
        requests:
          storage: 1Gi