apiVersion: v1
kind: Service
metadata:
  name: mongodbrouterservice
  labels:
    name: mongorouter
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    role: mongorouter

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodbrouterstateful
spec:
  selector:
    matchLabels:
      role: mongorouter
  serviceName: mongodbrouterservice
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: mongorouter
        replicaset: mongorouters
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50 #set to 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: replicaset
                  operator: In
                  values:
                  - mongorouters
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10      
      containers:
        - name: mongodroutercontainer
          image: mongo:3.6.2
          ports:
            - containerPort: 27017
          command:
            - "mongod"
            - "--configsvr"            
            - "--replSet"
            - "mongoreplicaset2config"
            - "--bind_ip_all"
            - "--port"
            - "27017"
          volumeMounts:           
            - name: mongodbrouterpvc
              mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodbrouterpvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 5Gi