apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodbshard2stateful
spec:
  selector:
    matchLabels:
      role: mongoshard2
  serviceName: mongodbshard2service
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: mongoshard2
        replicaset: mongoshards2
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50 #set to 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: replicaset
                  operator: In
                  values:
                  - mongoshards2
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10      
      containers:
        - name: mongodshard2container
          image: mongo:3.6.2
          command:
            - "mongod"
            - "--shardsvr"            
            - "--replSet"
            - "mongoreplicaset2shard"
            - "--bind_ip_all"
            - "--port"
            - "27017"
          ports:
          - containerPort: 27017
          volumeMounts:
          - name: mongodbshard2pvc
            mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodbshard2pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 20Gi
  
          