apiVersion: v1
kind: Service
metadata:
  name: mongodbconfigservice
  labels:
    name: mongoshard
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    role: mongoconfig

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodbconfigstateful
spec:
  selector:
    matchLabels:
      role: mongoconfig
  serviceName: mongodbconfigservice
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: mongoconfig
        replicaset: mongoconfigs
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50 #set to 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: replicaset
                  operator: In
                  values:
                  - mongoconfigs
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10      
      containers:
        - name: mongodconfigcontainer
          image: mongo:3.6.2
          command:
            - "mongod"
            - "--configsvr"            
            - "--replSet"
            - "mongoreplicaset1config"
            - "--bind_ip_all"
            - "--port"
            - "27017"
          ports:
            - containerPort: 27017
          volumeMounts:           
            - name: mongodbconfigpvc
              mountPath: /data/db
          resources:
            limits:
              cpu: "1"
              memory: "200Mi"
            requests:
              cpu: "0.1"
              memory: "100Mi"
  volumeClaimTemplates:
  - metadata:
      name: mongodbconfigpvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi