apiVersion: v1
kind: Service
metadata:
  name: mongodbshardservice
  labels:
    name: mongoshard
spec:
  selector:
    role: mongoshard
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodbshardstateful
spec:
  selector:
    matchLabels:
      role: mongoshard
  serviceName: mongodbshardservice
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: mongoshard
        replicaset: mongoshards
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50 #set to 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: replicaset
                  operator: In
                  values:
                  - mongoshards
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10      
      containers:
        - name: mongodshardcontainer
          image: mongo:3.6.2
          command:
            - "mongod"
            - "--shardsvr"            
            - "--replSet"
            - "mongoreplicaset1shard"
            - "--bind_ip_all"
            - "--port"
            - "27017"
          ports:
          - containerPort: 27017
          volumeMounts:
          - name: mongodbshardpvc
            mountPath: /data/db
          resources:
            limits:
              cpu: "1"
              memory: "200Mi"
            requests:
              cpu: "0.1"
              memory: "100Mi"
      nodeSelector:
        failure-domain.beta.kubernetes.io/region: us-central1
        failure-domain.beta.kubernetes.io/zone: us-central1-a
  volumeClaimTemplates:
  - metadata:
      name: mongodbshardpvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: us-central1-a-sc1
      resources:
        requests:
          storage: 2Gi
  
          