apiVersion: v1
kind: Service
metadata:
  name: mongodbroutersvc
  labels:
    name: mongorouter
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    role: mongorouter

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongosrouter
spec:
  selector:
    matchLabels:
      role: mongorouter
  serviceName: mongodbroutersvc
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: mongorouter
        replicaset: mongorouters
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: replicaset
                  operator: In
                  values:
                  - mongorouters
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10      
      containers:
        - name: mongosroutercontainer
          image: mongo:3.6.2
          command:
            - "mongos"
            - "--configdb"            
            - "mongoreplicaset1config/10.57.129.195:27017,10.57.129.131:27017,10.57.129.66:27017"
            - "--bind_ip_all"
            - "--port"
            - "27017"
          ports:
            - containerPort: 27017
          volumeMounts:           
            - name: mongodbrouterpvc
              mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodbrouterpvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 2Gi