apiVersion: v1
kind: Service
metadata:
  name: jojoservice
  labels:
    name: jojo
spec:
  selector:
    role: jojo
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jojostateful
spec:
  selector:
    matchLabels:
      role: jojo
  serviceName: jojoservice
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: jojo
        replicaset: jojo2
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50 #set to 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: replicaset
                  operator: In
                  values:
                  - jojo2
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10      
      containers:
        - name: mongodshardcontainer
          image: mongo:3.6.2
          command:
            - "mongod"
            - "--shardsvr"            
            - "--replSet"
            - "mongoreplicaset2shard"
            - "--bind_ip_all"
            - "--port"
            - "27017"
          ports:
          - containerPort: 27017
          volumeMounts:
          - name: jojopvc
            mountPath: /data/db
          resources:
            limits:
              cpu: "1"
              memory: "200Mi"
            requests:
              cpu: "0.1"
              memory: "100Mi"
      nodeSelector:
        failure-domain.beta.kubernetes.io/region: us-central1
        failure-domain.beta.kubernetes.io/zone: us-central1-b
  volumeClaimTemplates:
  - metadata:
      name: jojopvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: us-central1-b-sc1
      resources:
        requests:
          storage: 2Gi
  
          