---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvcmongoc20gb-101
  labels:
    app: mongodb-shard-node01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
